// Generated by Frozen Sand Particle Studio


textures/area3/poussiere
{
	qer_editorimage textures/area3/particule002
	q3map_cloneshader textures/area3/zzpoussiere_1
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0 0.016
	deformvertexes move -60.1189 163.284 0 square 0 1 0 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule002
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0 0.016
		alphagen const 1
	}
}

textures/area3/zzpoussiere_1
{
	qer_editorimage textures/area3/particule002
	q3map_cloneshader textures/area3/zzpoussiere_2
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0.0555556 0.016
	deformvertexes move 148.955 30.2727 0 square 0 1 0.0555556 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule002
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0.0555556 0.016
		alphagen const 1
	}
}

textures/area3/zzpoussiere_2
{
	qer_editorimage textures/area3/particule002
	q3map_cloneshader textures/area3/zzpoussiere_3
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0.111111 0.016
	deformvertexes move -96.9951 -122.18 0 square 0 1 0.111111 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule002
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0.111111 0.016
		alphagen const 1
	}
}

textures/area3/zzpoussiere_3
{
	qer_editorimage textures/area3/particule002
	q3map_cloneshader textures/area3/zzpoussiere_4
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0.166667 0.016
	deformvertexes move -118.875 -102.556 0 square 0 1 0.166667 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule002
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0.166667 0.016
		alphagen const 1
	}
}

textures/area3/zzpoussiere_4
{
	qer_editorimage textures/area3/particule002
	q3map_cloneshader textures/area3/zzpoussiere_5
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0.222222 0.016
	deformvertexes move 163.487 -77.6716 0 square 0 1 0.222222 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule002
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0.222222 0.016
		alphagen const 1
	}
}

textures/area3/zzpoussiere_5
{
	qer_editorimage textures/area3/particule002
	q3map_cloneshader textures/area3/zzpoussiere_6
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0.277778 0.016
	deformvertexes move -99.5628 -92.6458 0 square 0 1 0.277778 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule002
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0.277778 0.016
		alphagen const 1
	}
}

textures/area3/zzpoussiere_6
{
	qer_editorimage textures/area3/particule002
	q3map_cloneshader textures/area3/zzpoussiere_7
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0.333333 0.016
	deformvertexes move -115.632 -136.639 0 square 0 1 0.333333 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule002
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0.333333 0.016
		alphagen const 1
	}
}

textures/area3/zzpoussiere_7
{
	qer_editorimage textures/area3/particule002
	q3map_cloneshader textures/area3/zzpoussiere_8
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0.388889 0.016
	deformvertexes move 118.813 -96.3981 0 square 0 1 0.388889 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule002
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0.388889 0.016
		alphagen const 1
	}
}

textures/area3/zzpoussiere_8
{
	qer_editorimage textures/area3/particule002
	q3map_cloneshader textures/area3/zzpoussiere_9
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0.444444 0.016
	deformvertexes move -18.719 -185.056 0 square 0 1 0.444444 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule002
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0.444444 0.016
		alphagen const 1
	}
}

textures/area3/zzpoussiere_9
{
	qer_editorimage textures/area3/particule002
	q3map_cloneshader textures/area3/zzpoussiere_10
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0.5 0.016
	deformvertexes move 50.4338 135.946 0 square 0 1 0.5 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule002
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0.5 0.016
		alphagen const 1
	}
}

textures/area3/zzpoussiere_10
{
	qer_editorimage textures/area3/particule002
	q3map_cloneshader textures/area3/zzpoussiere_11
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0.555556 0.016
	deformvertexes move 123.682 88.3554 0 square 0 1 0.555556 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule002
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0.555556 0.016
		alphagen const 1
	}
}

textures/area3/zzpoussiere_11
{
	qer_editorimage textures/area3/particule002
	q3map_cloneshader textures/area3/zzpoussiere_12
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0.611111 0.016
	deformvertexes move 88.0829 -112.652 0 square 0 1 0.611111 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule002
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0.611111 0.016
		alphagen const 1
	}
}

textures/area3/zzpoussiere_12
{
	qer_editorimage textures/area3/particule002
	q3map_cloneshader textures/area3/zzpoussiere_13
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0.666667 0.016
	deformvertexes move 142.053 64.474 0 square 0 1 0.666667 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule002
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0.666667 0.016
		alphagen const 1
	}
}

textures/area3/zzpoussiere_13
{
	qer_editorimage textures/area3/particule002
	q3map_cloneshader textures/area3/zzpoussiere_14
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0.722222 0.016
	deformvertexes move -135.557 79.2037 0 square 0 1 0.722222 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule002
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0.722222 0.016
		alphagen const 1
	}
}

textures/area3/zzpoussiere_14
{
	qer_editorimage textures/area3/particule002
	q3map_cloneshader textures/area3/zzpoussiere_15
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0.777778 0.016
	deformvertexes move 80.5834 113.258 0 square 0 1 0.777778 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule002
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0.777778 0.016
		alphagen const 1
	}
}

textures/area3/zzpoussiere_15
{
	qer_editorimage textures/area3/particule002
	q3map_cloneshader textures/area3/zzpoussiere_16
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0.833333 0.016
	deformvertexes move -54.0768 159.059 0 square 0 1 0.833333 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule002
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0.833333 0.016
		alphagen const 1
	}
}

textures/area3/zzpoussiere_16
{
	qer_editorimage textures/area3/particule002
	q3map_cloneshader textures/area3/zzpoussiere_17
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0.888889 0.016
	deformvertexes move -115.145 74.2341 0 square 0 1 0.888889 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule002
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0.888889 0.016
		alphagen const 1
	}
}

textures/area3/zzpoussiere_17
{
	qer_editorimage textures/area3/particule002
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0.944444 0.016
	deformvertexes move 42.314 -157.412 0 square 0 1 0.944444 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule002
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0.944444 0.016
		alphagen const 1
	}
}

//*********************************************************************
//*********************************************************************

// Generated by Frozen Sand Particle Studio


textures/area3/poussiere3
{
	qer_editorimage textures/area3/particule003
	q3map_cloneshader textures/area3/zzpoussiere3_1
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0 0.016
	deformvertexes move 29.8426 -92.2953 0 square 0 1 0 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule003
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0 0.016
		alphagen const 1
	}
}

textures/area3/zzpoussiere3_1
{
	qer_editorimage textures/area3/particule003
	q3map_cloneshader textures/area3/zzpoussiere3_2
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0.0555556 0.016
	deformvertexes move 71.0353 38.9229 0 square 0 1 0.0555556 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule003
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0.0555556 0.016
		alphagen const 1
	}
}

textures/area3/zzpoussiere3_2
{
	qer_editorimage textures/area3/particule003
	q3map_cloneshader textures/area3/zzpoussiere3_3
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0.111111 0.016
	deformvertexes move -110.535 -10.1451 0 square 0 1 0.111111 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule003
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0.111111 0.016
		alphagen const 1
	}
}

textures/area3/zzpoussiere3_3
{
	qer_editorimage textures/area3/particule003
	q3map_cloneshader textures/area3/zzpoussiere3_4
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0.166667 0.016
	deformvertexes move -99.7453 7.13233 0 square 0 1 0.166667 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule003
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0.166667 0.016
		alphagen const 1
	}
}

textures/area3/zzpoussiere3_4
{
	qer_editorimage textures/area3/particule003
	q3map_cloneshader textures/area3/zzpoussiere3_5
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0.222222 0.016
	deformvertexes move -75.1544 -51.311 0 square 0 1 0.222222 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule003
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0.222222 0.016
		alphagen const 1
	}
}

textures/area3/zzpoussiere3_5
{
	qer_editorimage textures/area3/particule003
	q3map_cloneshader textures/area3/zzpoussiere3_6
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0.277778 0.016
	deformvertexes move 53.1178 78.7623 0 square 0 1 0.277778 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule003
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0.277778 0.016
		alphagen const 1
	}
}

textures/area3/zzpoussiere3_6
{
	qer_editorimage textures/area3/particule003
	q3map_cloneshader textures/area3/zzpoussiere3_7
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0.333333 0.016
	deformvertexes move 100.839 5.69253 0 square 0 1 0.333333 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule003
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0.333333 0.016
		alphagen const 1
	}
}

textures/area3/zzpoussiere3_7
{
	qer_editorimage textures/area3/particule003
	q3map_cloneshader textures/area3/zzpoussiere3_8
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0.388889 0.016
	deformvertexes move 34.4972 -104.451 0 square 0 1 0.388889 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule003
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0.388889 0.016
		alphagen const 1
	}
}

textures/area3/zzpoussiere3_8
{
	qer_editorimage textures/area3/particule003
	q3map_cloneshader textures/area3/zzpoussiere3_9
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0.444444 0.016
	deformvertexes move -110.271 39.1074 0 square 0 1 0.444444 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule003
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0.444444 0.016
		alphagen const 1
	}
}

textures/area3/zzpoussiere3_9
{
	qer_editorimage textures/area3/particule003
	q3map_cloneshader textures/area3/zzpoussiere3_10
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0.5 0.016
	deformvertexes move -111.935 37.3443 0 square 0 1 0.5 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule003
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0.5 0.016
		alphagen const 1
	}
}

textures/area3/zzpoussiere3_10
{
	qer_editorimage textures/area3/particule003
	q3map_cloneshader textures/area3/zzpoussiere3_11
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0.555556 0.016
	deformvertexes move -3.01975 111.959 0 square 0 1 0.555556 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule003
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0.555556 0.016
		alphagen const 1
	}
}

textures/area3/zzpoussiere3_11
{
	qer_editorimage textures/area3/particule003
	q3map_cloneshader textures/area3/zzpoussiere3_12
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0.611111 0.016
	deformvertexes move 18.0604 -119.645 0 square 0 1 0.611111 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule003
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0.611111 0.016
		alphagen const 1
	}
}

textures/area3/zzpoussiere3_12
{
	qer_editorimage textures/area3/particule003
	q3map_cloneshader textures/area3/zzpoussiere3_13
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0.666667 0.016
	deformvertexes move 74.9214 35.718 0 square 0 1 0.666667 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule003
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0.666667 0.016
		alphagen const 1
	}
}

textures/area3/zzpoussiere3_13
{
	qer_editorimage textures/area3/particule003
	q3map_cloneshader textures/area3/zzpoussiere3_14
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0.722222 0.016
	deformvertexes move -71.3274 -48.0458 0 square 0 1 0.722222 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule003
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0.722222 0.016
		alphagen const 1
	}
}

textures/area3/zzpoussiere3_14
{
	qer_editorimage textures/area3/particule003
	q3map_cloneshader textures/area3/zzpoussiere3_15
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0.777778 0.016
	deformvertexes move 56.7029 41.0461 0 square 0 1 0.777778 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule003
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0.777778 0.016
		alphagen const 1
	}
}

textures/area3/zzpoussiere3_15
{
	qer_editorimage textures/area3/particule003
	q3map_cloneshader textures/area3/zzpoussiere3_16
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0.833333 0.016
	deformvertexes move 6.0818 -97.8111 0 square 0 1 0.833333 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule003
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0.833333 0.016
		alphagen const 1
	}
}

textures/area3/zzpoussiere3_16
{
	qer_editorimage textures/area3/particule003
	q3map_cloneshader textures/area3/zzpoussiere3_17
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0.888889 0.016
	deformvertexes move 24.3362 -80.3974 0 square 0 1 0.888889 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule003
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0.888889 0.016
		alphagen const 1
	}
}

textures/area3/zzpoussiere3_17
{
	qer_editorimage textures/area3/particule003
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 triangle 0 1 0.944444 0.016
	deformvertexes move -46.6697 68.6363 0 square 0 1 0.944444 0.016
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/area3/particule003
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -2 0.944444 0.016
		alphagen const 1
	}
}


//*****************************************************
// fallscote
// Generated by Frozen Sand Particle Studio
// Mon Nov 16 04:08:33 2009
//*****************************************************

